// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVgIdAwlUXiNYs5dDntvJB2W18sLbZXA4',
    appId: '1:374301250242:web:479c6e2d948e513d5b215b',
    messagingSenderId: '374301250242',
    projectId: 'rifa-plus-2c038',
    authDomain: 'rifa-plus-2c038.firebaseapp.com',
    storageBucket: 'rifa-plus-2c038.firebasestorage.app',
    measurementId: 'G-02T231Q55D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCh1MJJL9eubBAcaqJF84LQh_3zNTXh5w',
    appId: '1:374301250242:android:a9ab5bf4d9b27e7a5b215b',
    messagingSenderId: '374301250242',
    projectId: 'rifa-plus-2c038',
    storageBucket: 'rifa-plus-2c038.firebasestorage.app',
  );
}
